# Setup
title: Gravity
tagline: Hitchhiking AI's Cosmos
description: AI를 여행하는 히치하이커를 위한 안내서
author: Beomyong Choi
url: "https://beomyongchoi.github.io"
baseurl: ''
paginate: 5
permalink: pretty

# About/contact
author:
  name: Beomyong Choi
  url: https://github.com/beomyongchoi
  email: dev.bychoi@gmail.com
  location: Seoul, Korea

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1.0

# 빌드 설정
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# 마크다운 설정
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 포스트 기본 설정
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "beomyong choi"
      comments: true

# 제외할 파일/폴더
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# 시간대 설정
timezone: Asia/Seoul
