# 기본 사이트 설정
title: BYAI
email: dev.bychoi@gmail.com
description: The time of man has come to an end
url: "https://beomyongchoi.github.io"
baseurl: ""

# Lanyon 테마를 위한 사용자 정보
author:
  name: beomyong choi
  url: https://github.com/beomyongchoi

# 빌드 설정
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# 페이지네이션
paginate: 10
paginate_path: "/page:num/"

# 마크다운 설정
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 포스트 기본 설정
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "beomyong choi"
      comments: true

# 제외할 파일/폴더
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# 시간대 설정
timezone: Asia/Seoul
