# Setup
title:               BYAI
tagline:             'AI Study Log'
description:         'The Hitchhiker's Guide to AI'
url:                 https://beomyongchoi.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              beomyong choi
  url:               https://github.com/beomyongchoi
  email:             dev.bychoi@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
